// Shared IT fields list — used by Auth, ProfileScreen, and Company components.
// Keep this as the single source of truth. The copies in Auth.tsx and ProfileScreen.tsx
// remain unchanged to avoid breaking existing Student flows.
export const IT_FIELDS = [
  "Frontend Development", "Backend Development", "Full Stack Development", "Web Development",
  "Mobile Development", "Android Development", "iOS Development", "Cross Platform Development",
  "Desktop Application Development", "Game Development", "Game Engine Development",
  "AR Development", "VR Development", "XR Development",
  "UI Design", "UX Design", "Product Design", "Graphic Programming",
  "Computer Graphics", "Animation Programming",
  "Software Engineering", "Software Architecture", "API Development",
  "Microservices Engineering", "Enterprise Software Development", "SaaS Development",
  "Embedded Systems", "Firmware Development", "Robotics", "IoT Development",
  "Mechatronics Programming", "Automation Engineering", "Industrial Software Engineering", "PLC Programming",
  "Cyber Security", "Ethical Hacking", "Penetration Testing", "Red Teaming",
  "Blue Teaming", "Purple Teaming", "Digital Forensics", "Malware Analysis",
  "Reverse Engineering", "Cryptography", "Application Security", "Cloud Security",
  "Network Security", "Information Security", "SOC Analysis", "Threat Hunting",
  "Incident Response", "OSINT",
  "Network Engineering", "Network Administration", "System Administration",
  "Linux Administration", "Windows Administration", "Virtualization",
  "Cloud Computing", "Cloud Architecture", "DevOps", "DevSecOps",
  "Site Reliability Engineering", "Infrastructure Engineering", "Platform Engineering",
  "Kubernetes Engineering",
  "Database Administration", "Database Engineering", "Data Engineering",
  "Big Data Engineering", "Business Intelligence", "Data Analysis",
  "Data Science", "Statistical Computing",
  "Artificial Intelligence", "AI Engineering", "Machine Learning", "Deep Learning",
  "Reinforcement Learning", "Generative AI", "Computer Vision", "NLP",
  "Speech Recognition", "Recommendation Systems", "MLOps", "Prompt Engineering",
  "AI Research",
  "Bioinformatics", "Computational Biology", "Health Informatics",
  "FinTech Development", "Blockchain Development", "Smart Contract Development",
  "Web3 Development", "Quantitative Computing", "Quantum Computing",
  "Telecom Engineering", "GIS Development", "Geographic Information Systems",
  "CAD Software Development", "ERP Development", "CRM Development",
  "QA Engineering", "Software Testing", "Test Automation",
  "Accessibility Engineering", "Human Computer Interaction",
  "Technical Support", "IT Support", "Solutions Architecture", "Technical Consulting",
  "Research Engineering", "Compiler Engineering", "Operating System Development",
  "Browser Engineering", "Kernel Development", "Distributed Systems Engineering",
  "High Performance Computing", "Parallel Computing", "Scientific Computing",
  "Audio Engineering", "Video Processing", "Streaming Systems Engineering",
  "Search Engine Engineering", "Ecommerce Engineering", "Payment Systems Engineering",
  "AdTech Engineering", "EdTech Development", "LegalTech Development",
  "GovTech Development", "Space Software Engineering", "Autonomous Systems Engineering",
  "Drone Software Development", "Simulation Engineering", "Digital Twin Engineering",
];

export const JOB_LEVELS = [
  "Intern",
  "Junior",
  "Mid-level",
  "Senior",
  "Experienced",
  "Lead",
  "Principal",
];
